// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **


/* eslint-disable node/no-missing-require, no-unused-vars */
const googleads = require('google-ads');

function main() {
  const accountBudgetProposalServiceClient = new googleads.AccountBudgetProposalServiceClient();
  const accountLinkServiceClient = new googleads.AccountLinkServiceClient();
  const adGroupAdLabelServiceClient = new googleads.AdGroupAdLabelServiceClient();
  const adGroupAdServiceClient = new googleads.AdGroupAdServiceClient();
  const adGroupAssetServiceClient = new googleads.AdGroupAssetServiceClient();
  const adGroupAssetSetServiceClient = new googleads.AdGroupAssetSetServiceClient();
  const adGroupBidModifierServiceClient = new googleads.AdGroupBidModifierServiceClient();
  const adGroupCriterionCustomizerServiceClient = new googleads.AdGroupCriterionCustomizerServiceClient();
  const adGroupCriterionLabelServiceClient = new googleads.AdGroupCriterionLabelServiceClient();
  const adGroupCriterionServiceClient = new googleads.AdGroupCriterionServiceClient();
  const adGroupCustomizerServiceClient = new googleads.AdGroupCustomizerServiceClient();
  const adGroupExtensionSettingServiceClient = new googleads.AdGroupExtensionSettingServiceClient();
  const adGroupFeedServiceClient = new googleads.AdGroupFeedServiceClient();
  const adGroupLabelServiceClient = new googleads.AdGroupLabelServiceClient();
  const adGroupServiceClient = new googleads.AdGroupServiceClient();
  const adParameterServiceClient = new googleads.AdParameterServiceClient();
  const adServiceClient = new googleads.AdServiceClient();
  const assetGroupAssetServiceClient = new googleads.AssetGroupAssetServiceClient();
  const assetGroupListingGroupFilterServiceClient = new googleads.AssetGroupListingGroupFilterServiceClient();
  const assetGroupServiceClient = new googleads.AssetGroupServiceClient();
  const assetGroupSignalServiceClient = new googleads.AssetGroupSignalServiceClient();
  const assetServiceClient = new googleads.AssetServiceClient();
  const assetSetAssetServiceClient = new googleads.AssetSetAssetServiceClient();
  const assetSetServiceClient = new googleads.AssetSetServiceClient();
  const audienceInsightsServiceClient = new googleads.AudienceInsightsServiceClient();
  const audienceServiceClient = new googleads.AudienceServiceClient();
  const batchJobServiceClient = new googleads.BatchJobServiceClient();
  const biddingDataExclusionServiceClient = new googleads.BiddingDataExclusionServiceClient();
  const biddingSeasonalityAdjustmentServiceClient = new googleads.BiddingSeasonalityAdjustmentServiceClient();
  const biddingStrategyServiceClient = new googleads.BiddingStrategyServiceClient();
  const billingSetupServiceClient = new googleads.BillingSetupServiceClient();
  const brandSuggestionServiceClient = new googleads.BrandSuggestionServiceClient();
  const campaignAssetServiceClient = new googleads.CampaignAssetServiceClient();
  const campaignAssetSetServiceClient = new googleads.CampaignAssetSetServiceClient();
  const campaignBidModifierServiceClient = new googleads.CampaignBidModifierServiceClient();
  const campaignBudgetServiceClient = new googleads.CampaignBudgetServiceClient();
  const campaignConversionGoalServiceClient = new googleads.CampaignConversionGoalServiceClient();
  const campaignCriterionServiceClient = new googleads.CampaignCriterionServiceClient();
  const campaignCustomizerServiceClient = new googleads.CampaignCustomizerServiceClient();
  const campaignDraftServiceClient = new googleads.CampaignDraftServiceClient();
  const campaignExtensionSettingServiceClient = new googleads.CampaignExtensionSettingServiceClient();
  const campaignFeedServiceClient = new googleads.CampaignFeedServiceClient();
  const campaignGroupServiceClient = new googleads.CampaignGroupServiceClient();
  const campaignLabelServiceClient = new googleads.CampaignLabelServiceClient();
  const campaignLifecycleGoalServiceClient = new googleads.CampaignLifecycleGoalServiceClient();
  const campaignServiceClient = new googleads.CampaignServiceClient();
  const campaignSharedSetServiceClient = new googleads.CampaignSharedSetServiceClient();
  const contentCreatorInsightsServiceClient = new googleads.ContentCreatorInsightsServiceClient();
  const conversionActionServiceClient = new googleads.ConversionActionServiceClient();
  const conversionAdjustmentUploadServiceClient = new googleads.ConversionAdjustmentUploadServiceClient();
  const conversionCustomVariableServiceClient = new googleads.ConversionCustomVariableServiceClient();
  const conversionGoalCampaignConfigServiceClient = new googleads.ConversionGoalCampaignConfigServiceClient();
  const conversionUploadServiceClient = new googleads.ConversionUploadServiceClient();
  const conversionValueRuleServiceClient = new googleads.ConversionValueRuleServiceClient();
  const conversionValueRuleSetServiceClient = new googleads.ConversionValueRuleSetServiceClient();
  const customAudienceServiceClient = new googleads.CustomAudienceServiceClient();
  const customConversionGoalServiceClient = new googleads.CustomConversionGoalServiceClient();
  const customerAssetServiceClient = new googleads.CustomerAssetServiceClient();
  const customerAssetSetServiceClient = new googleads.CustomerAssetSetServiceClient();
  const customerClientLinkServiceClient = new googleads.CustomerClientLinkServiceClient();
  const customerConversionGoalServiceClient = new googleads.CustomerConversionGoalServiceClient();
  const customerCustomizerServiceClient = new googleads.CustomerCustomizerServiceClient();
  const customerExtensionSettingServiceClient = new googleads.CustomerExtensionSettingServiceClient();
  const customerFeedServiceClient = new googleads.CustomerFeedServiceClient();
  const customerLabelServiceClient = new googleads.CustomerLabelServiceClient();
  const customerLifecycleGoalServiceClient = new googleads.CustomerLifecycleGoalServiceClient();
  const customerManagerLinkServiceClient = new googleads.CustomerManagerLinkServiceClient();
  const customerNegativeCriterionServiceClient = new googleads.CustomerNegativeCriterionServiceClient();
  const customerServiceClient = new googleads.CustomerServiceClient();
  const customerSkAdNetworkConversionValueSchemaServiceClient = new googleads.CustomerSkAdNetworkConversionValueSchemaServiceClient();
  const customerUserAccessInvitationServiceClient = new googleads.CustomerUserAccessInvitationServiceClient();
  const customerUserAccessServiceClient = new googleads.CustomerUserAccessServiceClient();
  const customInterestServiceClient = new googleads.CustomInterestServiceClient();
  const customizerAttributeServiceClient = new googleads.CustomizerAttributeServiceClient();
  const dataLinkServiceClient = new googleads.DataLinkServiceClient();
  const experimentArmServiceClient = new googleads.ExperimentArmServiceClient();
  const experimentServiceClient = new googleads.ExperimentServiceClient();
  const extensionFeedItemServiceClient = new googleads.ExtensionFeedItemServiceClient();
  const feedItemServiceClient = new googleads.FeedItemServiceClient();
  const feedItemSetLinkServiceClient = new googleads.FeedItemSetLinkServiceClient();
  const feedItemSetServiceClient = new googleads.FeedItemSetServiceClient();
  const feedItemTargetServiceClient = new googleads.FeedItemTargetServiceClient();
  const feedMappingServiceClient = new googleads.FeedMappingServiceClient();
  const feedServiceClient = new googleads.FeedServiceClient();
  const geoTargetConstantServiceClient = new googleads.GeoTargetConstantServiceClient();
  const googleAdsFieldServiceClient = new googleads.GoogleAdsFieldServiceClient();
  const googleAdsServiceClient = new googleads.GoogleAdsServiceClient();
  const identityVerificationServiceClient = new googleads.IdentityVerificationServiceClient();
  const invoiceServiceClient = new googleads.InvoiceServiceClient();
  const keywordPlanAdGroupKeywordServiceClient = new googleads.KeywordPlanAdGroupKeywordServiceClient();
  const keywordPlanAdGroupServiceClient = new googleads.KeywordPlanAdGroupServiceClient();
  const keywordPlanCampaignKeywordServiceClient = new googleads.KeywordPlanCampaignKeywordServiceClient();
  const keywordPlanCampaignServiceClient = new googleads.KeywordPlanCampaignServiceClient();
  const keywordPlanIdeaServiceClient = new googleads.KeywordPlanIdeaServiceClient();
  const keywordPlanServiceClient = new googleads.KeywordPlanServiceClient();
  const keywordThemeConstantServiceClient = new googleads.KeywordThemeConstantServiceClient();
  const labelServiceClient = new googleads.LabelServiceClient();
  const localServicesLeadServiceClient = new googleads.LocalServicesLeadServiceClient();
  const offlineUserDataJobServiceClient = new googleads.OfflineUserDataJobServiceClient();
  const paymentsAccountServiceClient = new googleads.PaymentsAccountServiceClient();
  const productLinkInvitationServiceClient = new googleads.ProductLinkInvitationServiceClient();
  const productLinkServiceClient = new googleads.ProductLinkServiceClient();
  const reachPlanServiceClient = new googleads.ReachPlanServiceClient();
  const recommendationServiceClient = new googleads.RecommendationServiceClient();
  const recommendationSubscriptionServiceClient = new googleads.RecommendationSubscriptionServiceClient();
  const remarketingActionServiceClient = new googleads.RemarketingActionServiceClient();
  const shareablePreviewServiceClient = new googleads.ShareablePreviewServiceClient();
  const sharedCriterionServiceClient = new googleads.SharedCriterionServiceClient();
  const sharedSetServiceClient = new googleads.SharedSetServiceClient();
  const smartCampaignSettingServiceClient = new googleads.SmartCampaignSettingServiceClient();
  const smartCampaignSuggestServiceClient = new googleads.SmartCampaignSuggestServiceClient();
  const thirdPartyAppAnalyticsLinkServiceClient = new googleads.ThirdPartyAppAnalyticsLinkServiceClient();
  const travelAssetSuggestionServiceClient = new googleads.TravelAssetSuggestionServiceClient();
  const userDataServiceClient = new googleads.UserDataServiceClient();
  const userListCustomerTypeServiceClient = new googleads.UserListCustomerTypeServiceClient();
  const userListServiceClient = new googleads.UserListServiceClient();
}

main();
